version: '3.9'

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: npdatabase
      POSTGRES_USER: npuser
      POSTGRES_PASSWORD: np@5233

volumes:
  postgres_data:
