# Generated by Django 5.1.7 on 2025-04-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('image_url', models.URLField()),
                ('category', models.CharField(choices=[('लोककथा', 'लोककथा'), ('ऐतिहासिक', 'ऐतिहासिक'), ('प्रेरक', 'प्रेरक')], max_length=20)),
                ('content', models.TextField()),
                ('read_time', models.IntegerField(help_text='Minutes to read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
